# src/GameSessionBundle/Resources/config/doctrine/CharacterSheetData.orm.yml
GameSessionBundle\Entity\CharacterSheetData:
    type: entity
    repositoryClass: GameSessionBundle\Entity\CharacterSheetDataRepository
#    inheritanceType: JOINED #SINGLE_TABLE
#    DiscriminatorColumn:
#        name: type
#        type: string
#    DiscriminatorMap:
#        character_sheet_data: GameSessionBundle\Entity\CharacterSheetData
#        character_sheet_data_field: GameSessionBundle\Entity\CharacterSheetDataField
#        character_sheet_data_group: GameSessionBundle\Entity\CharacterSheetDataGroup
    table: character_sheet_data
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 50
        datatype:
            type: string
            length: 50
        display_name:
            type: string
            length: 50
            nullable: TRUE
        value:
            type: string
            length: 50
            nullable: TRUE
    manyToOne:
        character_sheet:
            targetEntity: CharacterSheet
            inversedBy: character_sheet_data
            joinColumn:
                name: character_sheet_id
                referencedColumnName: id
        character_sheet_data_group:
            targetEntity: GameSessionBundle\Entity\CharacterSheetData
            inversedBy: character_sheet_data
            joinColumn:
                name: character_sheet_data_group_id
                referencedColumnName: id
    oneToMany:
        character_sheet_data:
            targetEntity: GameSessionBundle\Entity\CharacterSheetData
            mappedBy: character_sheet_data_group
            cascade: ["persist"]