# src/GameSessionBundle/Resources/config/doctrine/CharacterSheet.orm.yml
JJSR\Bundle\GameSessionBundle\Entity\CharacterSheet:
    type: entity
    repositoryClass: JJSR\Bundle\GameSessionBundle\Entity\CharacterSheetRepository
    table: character_sheet
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        character_sheet_template:
            targetEntity: CharacterSheetTemplate
            joinColumn:
                name: character_sheet_template_id
                referencedColumnName: id
        user:
            targetEntity: UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        character_sheet_data:
            targetEntity: CharacterSheetData
            mappedBy: character_sheet
            cascade: ["persist", "remove"]