# src/GameSessionBundle/Resources/config/doctrine/CharacterSheetTemplate.orm.yml
JJSR\Bundle\GameSessionBundle\Entity\CharacterSheetTemplate:
    type: entity
    repositoryClass: JJSR\Bundle\GameSessionBundle\Entity\CharacterSheetTemplateRepository
    table: character_sheet_template
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        version:
            type: integer
    manyToOne:
        rol_game:
            targetEntity: RolGame
            inversedBy: character_sheet_templates
            joinColumn:
                name: rol_game_id
                referencedColumnName: id