JJSR\Bundle\GameSessionBundle\Entity\GameSession:
    type: entity
    repositoryClass: JJSR\Bundle\GameSessionBundle\Entity\GameSessionRepository
    table: game_session
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        password: 
            type: string
            length: 4096
        start_date:
            type: datetime
        comments:
            type: text
            length: 200
            nullable: TRUE
    manyToOne:
        owner:
            targetEntity: UserBundle\Entity\User
            joinColumn:
                name: owner_id
                referencedColumnName: id
        rol_game:
            targetEntity: JJSR\Bundle\GameSessionBundle\Entity\RolGame
            joinColumn:
                name: rol_game_id
                referencedColumnName: id
        language:
            targetEntity: JJSR\Bundle\GameSessionBundle\Entity\Language
            joinColumn:
                name: language_id
                referencedColumnName: id            
            