# src/GameSessionBundle/Resources/config/doctrine/Language.orm.yml
JJSR\Bundle\GameSessionBundle\Entity\Language:
    type: entity
    repositoryClass: JJSR\Bundle\GameSessionBundle\Entity\LanguageRepository
    table: language
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
