#acme_topic:
#    channel: acme/channel
#    handler:
#        callback: 'acme.topic' #related to the getName() of your topic

#acme_rpc:
#    channel: sample/{method}
#    handler:
#        callback: 'acme.rpc' #related to the getName() or your RPC service
#    requirements:
#        method:
#            pattern: "[a-z_]+"

game_session_topic:
    channel: gameSession/{room}
    handler:
        callback: 'game_session.topic' #related to the getName() of your topic
    requirements:
        room:
            pattern: "^(0|[1-9][0-9]*)$"
