<?php

namespace JJSR\Bundle\GamingPlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserGameSessionConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGameSessionConnectionRepository extends EntityRepository
{
}

/*
 * 	public function findByUserAndGameSession($user_id, $game_session_id) 
	{
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT userGameSessionAssociation 
				FROM GamingPlatformBundle:UserGameSessionAssociation userGameSessionAssociation
				WHERE userGameSessionAssociation.user_id = '.$user_id.'
				AND userGameSessionAssociation.game_session_id = '.$game_session_id.''
		);

		try {
			return $query->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
	
	public function findByGameSession($game_session_id)
	{
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT userGameSessionAssociation
				FROM GamingPlatformBundle:UserGameSessionAssociation userGameSessionAssociation
				WHERE userGameSessionAssociation.game_session_id = '.$game_session_id.''
				);
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
 */