# ConnectionController
game_sessions:
    path:     /{_locale}/game/sessions
    defaults:  
        _controller: GamingPlatformBundle:Connection:displayGameSessions
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

login_game_session:
    path:     /{_locale}/game/session/{game_session_id}
    defaults:  
        _controller: GamingPlatformBundle:Connection:loginGameSession
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

#login_game_session_rejected:
#    path:     /{_locale}/game/login/rejected/{game_session_id}
#    defaults:  
#        _controller: GamingPlatformBundle:Connection:loginGameSessionRejected
#        _locale: %app.locale_default%
#    requirements:
#        _locale: %app.locales_string%

game_session_disconnected:
    path:     /{_locale}/game/disconected/{game_session_id}
    defaults:  
        _controller: GamingPlatformBundle:Connection:disconnected
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

game_session_already_connected:
    path:     /{_locale}/game/already-connected/{game_session_id}
    defaults:  
        _controller: GamingPlatformBundle:Connection:alreadyConnected
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%  

game_session_not_exist:
    path:     /{_locale}/game/not-exist/{game_session_id}
    defaults:  
        _controller: GamingPlatformBundle:Connection:gameSessionNotExist
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
# AdministrationController
gaming_platform_administration_main_menu:
    path:     /{_locale}/administration/gaming-platform-bundle
    defaults:  
        _controller: GamingPlatformBundle:Administration:administrationMenu
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%