imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: my_parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi: ~
    translator:
        fallbacks: ['%app.locale_default%']
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%app.locale_default%'
#    trusted_hosts: ~
#    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.pdo
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    validation:
        enable_annotations: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        scssphp: ~
#        scssphp:
#            file: %kernel.root_dir%/../vendor/leafo/scssphp/scss.inc.php
#            apply_to: '\.scss$'
        cssrewrite: ~
    bundles: [ AppBundle ]
    assets:
        bootstrap_js_and_jquery:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js'
        game_session_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jqueryui/themes/ui-darkness/*'
                - '%kernel.root_dir%/../vendor/drmonty/smartmenus/css/sm-core-css.css'
                - '%kernel.root_dir%/../vendor/drmonty/smartmenus/css/sm-clean.css'
        game_session_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jqueryui/jquery-ui.js'
                - '%kernel.root_dir%/../vendor/drmonty/smartmenus/js/jquery.smartmenus.js'
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css'
        bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff'
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff2'
            output: "fonts/glyphicons-halflings-regular.woff2"
#        game_session_js:
#            inputs:
##            vendor/components/jqueryui/themes/ui-darkness/jquery-ui.css
#                - '@AppBundle/Resources/public/js/thirdparty/jquery.js'
#                - '@AppBundle/Resources/public/js/thirdparty/jquery.ui.js'

braincrafted_bootstrap:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
    css_preprocessor: scssphp
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/sass/bootstrap.scss
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.scss.twig

#braincrafted_bootstrap:
#    output_dir:
#    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
#    jquery_path: %kernel.root_dir%/../vendor/components/jquery/jquery.js
#    css_preprocessor: lessphp # "less", "less", "sass" or "none"
#    fonts_dir: %kernel.root_dir%/../web/fonts
#    auto_configure:
#        assetic: true
#        twig: true
#        knp_menu: true
#        knp_paginator: true
#    customize:
#        variables_file: ~
#        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
#        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: true
    # the renderer to use, list is also available by default
    default_renderer: twig

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
        form:
            type: AppBundle\Form\Type\RegistrationType
            validation_groups: [ My_registration, Default ]
    profile:
        form:
            type: AppBundle\Form\Type\ProfileType
            validation_groups: [ My_profile, Default ]
    change_password:
        form:
            type: AppBundle\Form\Type\ChangePasswordType
            validation_groups: [ My_change_password, Default ]
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

#gos_web_socket:
#    server:
#        port: 8080        #The port the socket server will listen on
#        host: 127.0.0.1   #The host ip to bind to

gos_web_socket:
    server:
        port: '%gos_web_socket.port%'   #The port the socket server will listen on
        host: '%gos_web_socket.host%'   #The host ip to bind to
        router:
            resources:
                - '%kernel.project_dir%/src/AppBundle/Resources/config/pubsub/routing.yml'
    client:
        firewall: 'main' #can be an array of firewalls
        session_handler: '@session.handler.pdo'