parameters:
    mailer_user: jaimejesusserrano@gmail.com
    gos_web_socket.port: 1337
    gos_web_socket.host: 127.0.0.1
#
    app.locales_string: en|es
    app.locales:
        - en
        - es
    app.locale_default: en