rules:
    resource: "@RulesBundle/Resources/config/routing.yml"
    prefix:   /

game_session:
    resource: "@GameSessionBundle/Resources/config/routing.yml"
    prefix:   /

index:
    resource: "@IndexBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
app_index:     
    path: /{_locale}
    defaults:  
        _controller: "IndexBundle:Main:index"
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

#In order to use the built-in email functionality (confirmation of the account, 
#resetting of the password), you must activate and configure the SwiftmailerBundle.
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"