game_session:
    resource: "@GameSessionBundle/Resources/config/routing.yml"
    prefix:   /

index:
    resource: "@IndexBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
app_index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    
#fos_user:
    #resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    

#In order to use the built-in email functionality (confirmation of the account, 
#resetting of the password), you must activate and configure the SwiftmailerBundle.
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#user:
    #resource: "@UserBundle/Resources/config/routing.yml"
    #prefix:   /