# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    #providers:
        #our_db_provider:
            #entity:
                #class: UserBundle:User
                #property: username
                # if you're using multiple entity managers
                # manager_name: customer
    #providers:
        #in_memory:
            #memory:
                #users:
                    #Admin:
                        #password: nomelostoques
                        #roles: 'ROLE_ADMIN'
            

        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: web_platform_homepage
#                if you are using Symfony < 2.8, use the following config instead:
#                csrf_provider: form.csrf_provider
            logout:
                path: fos_user_security_logout
                target: web_platform_homepage
            anonymous: true
            
        #game_session:
            #pattern: ^/session/
            #form_login:
                #login_path:  /session/game_session_login
                #check_path:  /session/game_session_login_check


    access_control:
        - { path: ^/[^/]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/administration, role: ROLE_SUPER_ADMIN }
        - { path: ^/[^/]+/admin/, role: ROLE_ADMIN }
        - { path: ^/[^/]+/game, roles: ROLE_USER }
        
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        
