game_session_homepage:
    path:     /game
    defaults: { _controller: GameSessionBundle:Main:index }

create_game_session:
    path:     /game/createGameSesion
    defaults: { _controller: GameSessionBundle:Main:createGameSession }
    
join_session:
    path:     /game/session/{session_id}
    defaults: { _controller: GameSessionBundle:Main:joinSession }
    
game_sessions:
    path:     /game/sessions
    defaults: { _controller: GameSessionBundle:Main:gameSessions }
    
administration_game_session_homepage:
    path: /game/administration
    defaults: { _controller: GameSessionBundle:Administration:index }
    