create_game_session:
    path:     /{_locale}/game/createGameSesion
    defaults:  
        _controller: GameSessionBundle:Main:createGameSession
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

join_game_session:
    path:     /{_locale}/game/session/{game_session_id}
    defaults:  
        _controller: GameSessionBundle:Main:joinGameSession
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

login_game_session:
    path:     /{_locale}/game/session/login/{game_session_id}
    defaults:  
        _controller: GameSessionBundle:Main:loginGameSession
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
    
login_game_session_rejected:
    path:     /{_locale}/game/session/login/rejected/{game_session_id}
    defaults:  
        _controller: GameSessionBundle:Main:loginGameSessionRejected
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

game_session_disconnected:
    path:     /{_locale}/game/session/disconected/{game_session_id}
    defaults:  
        _controller: GameSessionBundle:Main:disconnected
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
game_session_removed:
    path:     /{_locale}/game/session/removed/{game_session_id}
    defaults:  
        _controller: GameSessionBundle:Main:removed
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
game_sessions:
    path:     /{_locale}/game/sessions
    defaults:  
        _controller: GameSessionBundle:Main:gameSessions
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
    
administration_game_session_homepage:
    path:     /{_locale}/game/administration
    defaults:  
        _controller: GameSessionBundle:Administration:index
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
edit_game_sessions:
    path:     /{_locale}/game/sessions/edit/{game_session_id}
    defaults:  
        _controller: GameSessionBundle:Main:editGameSession
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%