game_session_homepage:
    path:     /game
    defaults: { _controller: GameSessionBundle:Main:index }

create_game_session:
    path:     /game/createGameSesion
    defaults: { _controller: GameSessionBundle:Main:createGameSession }

join_game_session:
    path:     /game/session/{game_session_id}
    defaults: { _controller: GameSessionBundle:Main:joinGameSession }
    
login_game_session:
    path:     /game/session/login/{game_session_id}
    defaults: { _controller: GameSessionBundle:Main:loginGameSession }
    
login_game_session_rejected:
    path:     /game/session/login/rejected/{game_session_id}
    defaults: { _controller: GameSessionBundle:Main:loginGameSessionRejected }

game_sessions:
    path:     /game/sessions
    defaults: { _controller: GameSessionBundle:Main:gameSessions }
    
administration_game_session_homepage:
    path:     /game/administration
    defaults: { _controller: GameSessionBundle:Administration:index }