services:
#    game_session.example:
#        class: GameSessionBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#    acme_hello.topic_sample_service:
#        class: GameSessionBundle\Topic\AcmeTopic
#        tags:
#            - { name: gos_web_socket.topic }

    game_session.topic:
        class: GameSessionBundle\Topic\GameSessionTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: [ @gos_web_socket.websocket.client_manipulator ] #@gos_web_socket.client_storage
 
    game_session.chat_topic:
        class: GameSessionBundle\Topic\ChatTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: [ @gos_web_socket.router.wamp, @gos_web_socket.websocket.client_manipulator ] #@gos_web_socket.client_storage

    game_session.import_character_sheet_topic:
        class: GameSessionBundle\Topic\ImportCharacterSheetTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: [ @gos_web_socket.websocket.client_manipulator ]
        
    game_session.functionality_character_sheet_topic:
        class: GameSessionBundle\Topic\FunctionalityCharacterSheetTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: [ @gos_web_socket.router.wamp, @gos_web_socket.websocket.client_manipulator ]
        
    game_session.conection_topic:
        class: GameSessionBundle\Topic\ConectionTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: [ @gos_web_socket.websocket.client_manipulator ]

#    acme_hello.rpc_sample_service:
#        class: GameSessionBundle\Rpc\AcmeRpc
#        tags:
#            - { name: gos_web_socket.rpc }