services:
    game_session.topic:
        class: GameSessionBundle\Topic\GameSessionTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: 
            - @gos_web_socket.websocket.client_manipulator
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator.builder
            - @translator.default
#           - @gos_web_socket.client_storage
            
#    rol_game_form:
#        class: GameSessionBundle\Form\RolGameType
#        arguments: 
#            - @doctrine.orm.entity_manager        
#        calls:
#            - [setEntityManager, [@doctrine.orm.entity_manager]]

#    acme_hello.rpc_sample_service:
#        class: GameSessionBundle\Rpc\AcmeRpc
#        tags:
#            - { name: gos_web_socket.rpc }