# GameSessionBundle/Resources/config/validation.yml
GameSessionBundle\Entity\GameSession:
    properties:
        id:
            - IsNull: ~
        name:
            - NotBlank:
                message: name.not_blank
            - Length:
                min: 5
                max: 30
                minMessage: name.minimum_characters
                maxMessage: name.maximum_characters
        owner_user:
            - IsNull: ~
        password:
            - NotBlank:
                message: plainPassword.not_blank
                groups: [Login]
            - Length:
                min: 6 
                max: 30
                minMessage: password.minimum_characters
                maxMessage: password.maximum_characters
                groups: [Login]
        start_date:
            - IsNull: ~         
        rol_game:
            - NotBlank:
                message: rol_game.not_blank
        language:
            - NotBlank:
                message: language.not_blank
        comments:
            - Length:
                max: 200
                maxMessage: comments.maximum_characters