# GameSessionBundle/Resources/config/validation.yml
GameSessionBundle\Entity\GameSession:
    properties:
        id:
            - IsNull: ~
        name:
            - NotBlank: ~
            - Length:
                min: 5
                max: 30
                minMessage: "El nombre de la sesión must be at least {{ limit }} characters long"
                maxMessage: "El nombre de la sesión cannot be longer than {{ limit }} characters"
        owner_user:
            - IsNull: ~
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 30
                minMessage: "La contraseña de la sesión must be at least {{ limit }} characters long"
                maxMessage: "La contraseña de la sesión cannot be longer than {{ limit }} characters"   
        start_date:
            - IsNull: ~         
        rol_game:
            - NotBlank: ~
        language:
            - NotBlank: ~
        comments:
            - Length:
                max: 200
                maxMessage: "El comentario de la sesión cannot be longer than {{ limit }} characters"
                

GameSessionBundle\Entity\PasswordGameSession:
    properties:
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 30
                minMessage: "La contraseña de la sesión must be at least {{ limit }} characters long"
                maxMessage: "La contraseña de la sesión cannot be longer than {{ limit }} characters"    