# src/UserBundle/Resources/config/doctrine/User.orm.yml
UserBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 30
            unique: true
        real_name:
            type: string
            length: 30
        real_surname:
            type: string
            length: 60
        email:
            type: string
            length: 60
            unique: true
        password: 
            type: string
            length: 64
        registration_date:
            type: datetime
        last_login:
            type: datetime
