services:
#    user.example:
#        class: UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    user.form.registration:
        class: UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
            
    user.profile.form.type:
        class: UserBundle\Form\Type\ProfileType
#        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_profile }
            
    user.change_password.form.type:
        class: UserBundle\Form\Type\ChangePasswordType
        tags:
            - { name: form.type, alias: user_change_password }
