# UserBundle/Resources/config/validation.yml
UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: email
            message: "The email is already in use"
            groups: [My_registration, My_profile]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: username
            message: "The username is already in use"
            groups: [My_registration, My_profile]
    properties:
        id:
            - IsNull:
                groups: [My_registration]
        username:
            - NotBlank:
                message: Username should not be blank
                groups: [My_registration]
            - Length:
                min: 5
                max: 30
                minMessage: "Username must be at least {{ limit }} characters long"
                maxMessage: "Username cannot be longer than {{ limit }} characters"
                groups: [My_registration, My_profile]
        real_name:
            - NotBlank:
                message: Real name should not be blank
                groups: [My_registration, My_profile]
            - Length:
                min: 2
                max: 255
                minMessage: "Real name must be at least {{ limit }} characters long"
                maxMessage: "Real name cannot be longer than {{ limit }} characters"
                groups: [My_registration, My_profile]
        real_surname:
            - NotBlank:
                message: Real surname should not be blank
                groups: [My_registration, My_profile]
            - Length:
                min: 2
                max: 255
                minMessage: "Real surname must be at least {{ limit }} characters long"
                maxMessage: "Real surname cannot be longer than {{ limit }} characters"
                groups: [My_registration, My_profile]
        email:
            - NotBlank:
                message: Email should not be blank
                groups: [My_registration, My_profile]
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
                groups: [My_registration, My_profile]
            - Length:
                min: 4
                max: 60
                minMessage: "Email must be at least {{ limit }} characters long"
                maxMessage: "Email cannot be longer than {{ limit }} characters"
                groups: [My_registration, My_profile]
        plainPassword:
            - NotBlank:
                message: Password Should not be blank
                groups: [My_registration, My_change_password]
            - Length:
                min: 6 
                max: 4096
                minMessage: "Password must be at least {{ limit }} characters long"
                maxMessage: "Password cannot be longer than {{ limit }} characters"
                groups: [My_registration, My_change_password]
        #registration_date:
            #- IsNull: ~
        #last_login:
            #- IsNull: ~
        terms_accepted:
            - IsTrue:
                message: You must agree to the terms and conditions to register
                groups: [My_registration]
            
#UserBundle\Form\Model\Registration:
#    properties:
#        user:
#            - Type:
#                type: UserBundle\Entity\User
#                message: "The value {{ value }} is not a valid {{ type }}."
#            - Valid: ~
#        terms_accepted:
#            - NotBlank: ~
#            - 'True':
#                message: Debes aceptar los términos y condiciones