# UserBundle/Resources/config/validation.yml
UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: email
            message: email.in_use
            groups: [My_registration, My_profile]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: username
            message: username.in_use
            groups: [My_registration, My_profile]
    properties:
        id:
            - IsNull:
                groups: [My_registration]
        username:
            - NotBlank:
                message: username.not_blank
                groups: [My_registration]
            - Length:
                min: 5
                max: 30
                minMessage: username.minimum_characters
                maxMessage: username.maximum_characters
                groups: [My_registration, My_profile]
        real_name:
            - NotBlank:
                message: real_name.not_blank
                groups: [My_registration, My_profile]
            - Length:
                min: 2
                max: 255
                minMessage: real_name.minimum_characters
                maxMessage: real_name.maximum_characters
                groups: [My_registration, My_profile]
        real_surname:
            - NotBlank:
                message: real_surname.not_blank
                groups: [My_registration, My_profile]
            - Length:
                min: 2
                max: 255
                minMessage: real_surname.minimum_characters
                maxMessage: real_surname.maximum_characters
                groups: [My_registration, My_profile]
        email:
            - NotBlank:
                message: email.not_blank
                groups: [My_registration, My_profile]
            - Email:
                message: email.not_valid
                checkMX: true
                groups: [My_registration, My_profile]
            - Length:
                min: 4
                max: 60
                minMessage: email.minimum_characters
                maxMessage: email.maximum_characters
                groups: [My_registration, My_profile]
        plainPassword:
            - NotBlank:
                message: plainPassword.not_blank
                groups: [My_registration, My_change_password]
            - Length:
                min: 6 
                max: 4096
                minMessage: plainPassword.minimum_characters
                maxMessage: plainPassword.maximum_characters
                groups: [My_registration, My_change_password]
        terms_accepted:
            - IsTrue:
                message: terms_accepted.is_true
                groups: [My_registration]
