services:
    add_character_sheet_menu_type.service:
        class: AppBundle\Form\Type\AddCharacterSheetMenuType
        arguments:
            - @doctrine.orm.entity_manager
            - @translator.default

    app.form.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.profile.form.type:
        class: AppBundle\Form\Type\ProfileType
#        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_profile }

    app.change_password.form.type:
        class: AppBundle\Form\Type\ChangePasswordType
        tags:
            - { name: form.type, alias: user_change_password }