services:
    add_character_sheet_menu_type.service:
        class: AppBundle\Form\Type\AddCharacterSheetMenuType
        arguments:
            - @doctrine.orm.entity_manager
            - @translator.default

    app.form.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }