<?php
namespace JJSR\Bundle\GameSessionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterSheetTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSheetTemplateRepository extends EntityRepository
{
}
