services:
#    index.example:
#        class: IndexBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    index.menu.voter.request:
        class: IndexBundle\Menu\RequestVoter
        tags:
            - { name: knp_menu.voter }
        arguments: [ @request_stack ]