<?php

namespace AppBundle\Entity;

/**
 * CharacterSheetDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSheetDataRepository extends \Doctrine\ORM\EntityRepository
{
}
