<?php

namespace AppBundle\Entity;

/**
 * CharacterSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSheetRepository extends \Doctrine\ORM\EntityRepository
{
}
