<?php

namespace AppBundle\Entity;

/**
 * CharacterSheetTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSheetTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
