<?php

namespace AppBundle\Entity;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT language FROM GameSessionBundle:Language language'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
