<?php

namespace AppBundle\Entity;

/**
 * UserGameSessionConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGameSessionConnectionRepository extends \Doctrine\ORM\EntityRepository
{
}
