<?php

namespace GameSessionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterSheetDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSheetDataRepository extends EntityRepository
{
}
