# GameSessionController
create_game_session:
    path:     /{_locale}/game/create-game-session
    defaults:  
        _controller: GameSessionBundle:GameSession:createGameSession
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
#edit_game_sessions:
#    path:     /{_locale}/game/session/edit/{game_session_id}
#    defaults:  
#        _controller: GameSessionBundle:GameSession:editGameSession
#        _locale: %app.locale_default%
#    requirements:
#        _locale: %app.locales_string%

# AdministrationController
game_session_administration_main_menu:
    path:     /{_locale}/administration/game-session-bundle
    defaults:  
        _controller: GameSessionBundle:Administration:administrationMenu
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
game_session_add_all_default_data:
    path:     /{_locale}/administration/game-session-bundle/add-all-default-data
    defaults:  
        _controller: GameSessionBundle:Administration:addAllDefaultData
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
game_session_delete_all_default_data:
    path:     /{_locale}/administration/game-session-bundle/delete-all-default-data
    defaults:  
        _controller: GameSessionBundle:Administration:deleteAllDefaultData
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
manage_character_sheet_templates:
    path:     /{_locale}/administration/game-session-bundle/character-sheet-templates
    defaults:  
        _controller: GameSessionBundle:Administration:manageCharacterSheetTemplates
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
add_character_sheet_template:
    path:     /{_locale}/administration/game-session-bundle/add-character-sheet-template
    defaults:  
        _controller: GameSessionBundle:Administration:addCharacterSheetTemplate
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
remove_character_sheet_template:
    path:     /{_locale}/administration/game-session-bundle/remove-character-sheet-template/{character_sheet_template_id}
    defaults:  
        _controller: GameSessionBundle:Administration:removeCharacterSheetTemplate
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
edit_character_sheet_template:
    path:     /{_locale}/administration/game-session-bundle/edit-character-sheet-template/{character_sheet_template_id}
    defaults:  
        _controller: GameSessionBundle:Administration:editCharacterSheetTemplate
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
              
# CharacterSheetController              
add_character_sheet_menu:
    path:     /{_locale}/game/add-character-sheet
    defaults:  
        _controller: GameSessionBundle:CharacterSheet:addCharacterSheetMenu
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

add_character_sheet:
    path:     /{_locale}/game/add-character-sheet/{rol_game_name}/{character_sheet_template_name}
    defaults:  
        _controller: GameSessionBundle:CharacterSheet:addCharacterSheet
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
delete_character_sheet:
    path:     /{_locale}/game/delete-character-sheet/{character_sheet_id}
    defaults:  
        _controller: GameSessionBundle:CharacterSheet:deleteCharacterSheet
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%

character_sheets_list:
    path:     /{_locale}/game/character-sheets-list
    defaults:  
        _controller: GameSessionBundle:CharacterSheet:characterSheetList
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%
        
edit_character_sheet:
    path:     /{_locale}/game/character-sheet/edit/{character_sheet_id}
    defaults:  
        _controller: GameSessionBundle:CharacterSheet:editCharacterSheet
        _locale: %app.locale_default%
    requirements:
        _locale: %app.locales_string%